version: '3.8'

services:
  firefly-bot:
    restart: unless-stopped
    container_name: firefly-telegram-bot
    build: .
    env_file: 
      - .env
    volumes:
      - ./data:/usr/src/app/data
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true